auto: true
permalink: /:title.html
markdown: kramdown

uri: http://stas.github.com
author: Stas Sușcov
email: stas@nerd.ro
title: Stas Sușcov Journal
tagline: Boy meets computer...
face: http://gravatar.com/avatar/39639fde05c65fae440b775989e55006?s=70
face_alt: Stas's face
intro: |
  Hi, my name is Stas and this is my unfancy blog.
  <br>
  Feel free to check out the pages/links below 
  if you care to find out about my doings or habbits.

button_left: <a href="http://feeds.nerd.ro/stas">Blog <strong>Feed</strong></a>
button_mid: <a href="http://twitter.com/suscov">My <strong>Twitter</strong></a>
button_right: <a href="http://github.com/stas">My <strong>GitHub</strong></a>
copyright_note: Content under <a href="http://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a> license.
